#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#     CONFIGURATION FILE FOR FRAGMENT ANALYSIS PIPELINE         #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#
# INSTRUCTIONS:
# 1. Edit the file paths in Section 1 to match your project.
# 2. Configure your experimental design in Section 2.
#    - This is the MOST IMPORTANT section.
#    - See the "HOW-TO SWITCH" guides below.
# 3. Adjust analysis parameters in Section 3.
# 4. Save this file as 'config.yml' in your main project folder.
#
# YAML syntax:
# - Use 'null' (without quotes) for empty fields.
# - Indentation matters! Use spaces, not tabs.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# --- 1. File Paths & Directories ---
# All paths should be relative to your main project directory.
paths:
  fsa_folder: "1_raw_data"
  output_dir_base: "4_analysis_output"
  external_data_path: 
  - "3_romeo_output/ADD_ROMEO_FILE_HERE" # enter the name of your romeo export, can add more lines if need to combine files

# Platemap configuration section
platemap:
  format: "stacked_excel"   # Specify the format: "stacked_excel", "tidy_excel" or "tidy_csv""
  path: 
  - "2_metadata/ADD_PLATEMAP_FILENAME_HERE"   # Provide the path to the corresponding file
  #- "2_metadata/SECOND_PLATEMAP_FILENAME_HERE"
  
  # Matches "AnyProjectCode_Plate1", "CDK5_plate2", "JO_PLATE3"
  # [^_]+             -> Matches any characters that are NOT an underscore (the Project Code)
  # _                 -> The separator
  # [Pp][Ll][Aa][Tt][Ee] -> Matches "plate" in any case (Plate, plate, PLATE)
  # \d+               -> Matches the number
  stacked_excel_identifier: '(RPE-\d+)'

# --- 2. FSA Filename Parsing Rules ---
fsa_filename_parsing: # Required for finding the Plate and Well from .fsa filenames.
  plate_number:
    separator: "-"      # Put a dash between the pieces we find
    part_1:
      method: "split"
      delimiter: "_"
      position: 2       # Extracts "ExpA"
    part_2:
      method: "split"
      delimiter: "_"
      position: 3       # Extracts "Run1"

    # method: "regex"
    # pattern: "(?<=\\d{4}-\\d{2}-\\d{2}-)[^_]+(?=_[A-H][0-9]{2}_)"   
    
  well_name:
    method: "regex"
    pattern: "[A-H][0-9]{2}"     # This pattern finds A01, H12, etc.

# --- 3. Settings for External Program's Settings File ---
# These values are written *into* the settings file generated by Script 1.
custom_settings:
  flank: 110
  repeat_unit: 3
  correction: 2.7724117
  pathogenic_threshold: 36
  ii_threshold_method: "relative"
  ii_threshold_height: 0.2 # Threshold for instability index
  ii_threshold_area: 0.2
  target_channel: "channel_1"
  target_start: 115 # Window start for finding the expanded allele
  target_end: 135 # Window end for finding the expanded allele
  plot_start: 0
  plot_end: 160
  control_rpt: null
  group_control_sample_prefix: null
  exclude: null

# --- 4. Experimental Design Definition ---
# This section controls the entire analysis logic.

# Define the column names from splitting your 'sample_name' (from the platemap).
# The order MUST match the order in your sample names (e.g., "WT_C1_D1_D7_R1_P1")
# Can add up to 6 variables here
sample_name_columns:
  - "genotype"
  - "clone"
  - "rep"
  - "days"
  - "pcr"

key_variables:
  experiment_style: "clone"  # use "clone" for standard experiments or "treatment" if using drugs/ASOs etc. 
  time_variable: "days" # typically days or weeks (could also be passage)
  primary_group_var: "genotype" # the main variable you are testing, usually genotype but could be CAG length etc.
  secondary_group_var: "clone" # grouping variable, for CRISPR experiments, usually clone but could be differentiation etc.
  optional_grouping_var: "rep" # for iPSC/RPE/dividing cells where the each well rep is kept independent
  model_fixed_effects:
  - "genotype" # the main effect you want to look at
  repeated_measure_var: "rep"  # in a dividing cell experiment, the timepoints are not strictly independent from each other
  optional_random_effect: # background variation 
  - "clone" # random effects you want to acccount for e.g. clone, differentiation (if not a batch effect, see below)
  optional_crossed_effect: null #this would be differentiation or batch i.e. running the exact experiment multiple times,
  nesting_structure: "clone/rep" # specify how to variables are nested e.g. multiple reps within the clone, multiple differentiations with a clone etc., not essential

# --- 5. Analysis & Plotting Parameters ---
parameters:
  remove_bio_outliers: false   # Set to true to replace bio outliers with NA
  remove_tech_outliers: false  # Set to true to replace tech (PCR) outliers with NA
  peak_height_threshold: 40  # RFU value below which peaks are excluded

  # --- Baseline Normalization Method ---
  # Defines how Day 0 baselines are calculated.
  # Options:
  #  - "group": (For Clones) Calculates a separate D0 baseline for each unique group (e.g., WT-CloneA, WT-CloneB), works if you have one run per clone (no duplications)
  #  - "genotype": Calculates one D0 baseline for the each primary group (e.g., all WT baselines are averaged, all KO baselines are averaged).
  #  - "global_control": (For Treatments) Uses *one* specific control group (defined below) as the D0 baseline for ALL samples, if you just have one genotype for treatment
  #  - "custom": Can be used if you have a more complicated baseline structure e.g. multiple runs of the same clone that should have separate baselines
  baseline_grouping_level: "custom"
  baseline_group_vars:
  - "genotype"
  - "clone"
  - "rep"
  share_baselines: false # mostly for treatment, set to TRUE if you want the baselines to be shared across all treatment conditions
  pool_baselines_across: null # which variable are the baselines shared across (usually treatment)
  
  # --- Settings for "global_control" method ONLY --- otherwise ignore
  global_control_group:
    variable: "treatment"     # The column name (from 'sample_name_columns') that contains the control.
    level: "VEH"    # The specific level that identifies the control group.
    
# --- Fold Change Control Conditions ---
  fold_change_controls:
   
    baseline_genotype: "WT"   # For Clone Experiments: Which Genotype is the baseline? (e.g., "WT")
    baseline_treatment: null    # FOR Treatment Experiments: Which drug dose represents the "Untreated" baseline? (e.g., "0")
  
  # (NEW) Control whether to rename the secondary variable to "Rank 1, Rank 2..."
  # Set to TRUE for Clone experiments (masks IDs).
  # Set to FALSE for Treatment experiments (keeps "100nM", "200nM" labels).
  use_pseudo_clones: true # typically keep as true for CRISPR/clone experiments 

# --- 6. Sample Exclusion Criteria ---
# List samples to remove from the analysis *after* loading.
# The script removes rows that match ALL criteria in a single entry.
# Set to 'null' to disable.
#
exclusions:
#   - { genotype: "WT", clone: "C" }  # Excludes only clone C from the WT group
#   - { rep: "3" }                   # Excludes all samples that are replicate 3
#   - { treatment: "VEH", days: "14" } # Excludes VEH at day 14


# --- 7. Factor Level Ordering ---
# Define the desired order for variables in plots and models.
# If a variable is not listed, it will be ordered alphabetically.
# The first item in the list becomes the reference level in models.
factor_levels:
  # genotype: ["WT", "S126A", "S126D", "P127R", "YFAA", "MIM", "D960A", "FAN1KO", "CTRL"]
  # clone: ["C1", "C4", "C8"]
  
value_renaming: # "platemap name": "Pretty name"
  # "WT": "WT"
  # "S126DHom": "S126D"
  # "P127RHom": "P127R" 
  # "FAN1KO": "FAN1 KO"

color_mapping: #Use Pretty name here is added
  # "WT": "#0072B2" #blue
  # "S126D": "#CC79A7" #pink
  # "P127R": "#009E73" #green
  # "FAN1 KO": "#F0E442" #yellow 
  # "S126A": "#D55E00" #orange
  # "MIM": "#7570B3" #purple
  # "D960A": "#99E472" #lightgreen
  # "YFAA": "#0B31A5" #darkblue
  # "CTRL": "#4B4C4E" #grey

# --- 8. Plotting Settings ---
# Settings to control the appearance of plots in 02_generate_plots.R
plot_settings:
  # Define the breaks for the x-axis (e.g., [0, 5, 10])
  # Set to 'null' to let ggplot decide automatically
  x_axis_breaks: [0, 5, 10, 15, 20, 25, 30, 35, 40] # Specify 

  # Define breaks for log-scale Y-axes (e.g., peak height)
  # These are the *actual* numbers (not the log10 values)
  y_axis_log_breaks: [10, 50, 100, 200, 500,  1000]
  
  time_bin_width: 4 # How to group timepoints if you have similar timepoints e.g. Day 7, Day 8, Day 13, Day 14, gets grouped every 4 days to simplify plotting

#  DEFINE LABEL FORMATS
label_parameters:
  # Which style to use; "exploratory" or "publication"
  active_label_style: "exploratory"

label_formats:
  # Available Variables for String Templates:
  #   {primary}   or {geno}  -> Primary variable (e.g., WT, FAN1 KO)
  #   {secondary} or {treat} -> Secondary variable (e.g., Vehicle, 100nM ASO)
  #   {base}                 -> Calculated average baseline CAG size (rounded)

  # Examples you can swap between:
  # publication: "{geno} - {treat}"               # Results in: "WT - 100nM"
  # publication: "{treat} ({base}Q)"              # Results in: "100nM (140Q)"
  # publication: "{geno} | {treat} (Start: {base}Q)" # Results in: "WT | 100nM (Start: 140Q)"
  
  publication: "{geno}"
  exploratory: "{geno} ({base}Q)"
  
# --- 9. Trace Plotting Settings (Script 05) ---
trace_settings:
  # Path to the exported Text file from GeneMapper (The table in your screenshot)
  genemapper_file_path:
  - "1_raw_data/TXT_FROM_GENEMAPPER_1"
  - "1_raw_data/TXT_FROM_GENEMAPPER_2"

  # X-axis limits for the trace plots (in CAG repeat units, NOT bp)
  x_limits: [105, 150]
  wt_x_limits: [0, 36]
  
  publication_limits:
    wt_lims: [10, 25]
    exp_lims: [105, 140]

# --- 10. Variable Pretty Labels
#
# Define "pretty" labels for plots in Script 03.
# The 'key' must be the *exact* column name in the R data table.
# The 'value' is the pretty label you want on the plot.

# Maps column names from the external program's file to names used in R. You can add more variables if desired e.g. WT modal CAG, mean CAG etc.
response_variables: 
  # R_name: "External_Program_Column_Name"
  mode_change: "mode_change"
  mode: "target_peak_rpt"
  instability_index: "ii_c"
  instability_index_change: "instability_index_change" #this is calculated
  expansion_index: "expi_c"
  expansion_index_change: "expansion_index_change" #this is calculated

# 'Pretty' labels for plots. Must match the R_names above.
response_variable_labels:
  # R_name: "Pretty Name"
  mode_change: "Change in Modal CAG"
  mode: "Modal CAG"
  instability_index: "Instability Index"
  instability_index_change: "Change in Instability Index"
  expansion_index: "Expansion Index"
  expansion_index_change: "Change in Expansion Index"

# Short aliases for filenames to prevent path length errors. Used for filenames, can be changed but keep short and brief
# Must match the R_names from 'response_variables'.
response_variable_shortnames:
  mode_change: "mode_change"
  mode: "mode"
  instability_index: "ii_c"
  instability_index_change: "ii_change"
  expansion_index: "expi"
  expansion_index_change: "expi_change"

variable_pretty_labels:
  # Key variables
  genotype: "Genotype" # This will be overwritten by str_to_title in the script

  # Calculated variables from Script 1 & 2
  baseline_mode: "Baseline Modal CAG"
  slope_mode_change: "Slope (Mode Change)"
  slope_mode: "Slope (Mode)"
  slope_instability_index: "Slope (Instability Index)"
  slope_peak_instability: "Slope (Peak Instability)"

  # External metadata examples (add your own)
  RPE1_mode_change: "RPE1 - Slope (Mode Change)"
  RPE1_ii_c: "RPE1 - Slope (Instability Index)"
  protein_expression: "Protein Expression"
  dividing_cells: "% Dividing Cells"
  avg_protein_level: "Avg. Protein Level"
  rna_seq_score: "RNA-Seq Score"

# --- 11. External Metadata files for correlation

# Optional: Paths to Excel files with *additional* data for correlation.
# The script will join this data based on your key variables.
# Set to 'null' if not used.

external_metadata:
  # --- For data at the "group" level ---
  # (e.g., clone-by-clone data, treatment-by-replicate data)
  # File MUST contain 'primary_group_var' AND 'secondary_group_var' columns.
  # Example: "R_Analysis/2_metadata/clone_metadata.xlsx"
  group_level_path: "R_Analysis/2_metadata/Cell_Expansion_Matrix_Baseline.xlsx"

  # --- For data at the "genotype" level ---
  # (e.g., one value per genotype from a different experiment)
  # File MUST contain the 'primary_group_var' column.
  # Example: "R_Analysis/2_metadata/genotype_metadata.xlsx"
  genotype_level_path: "R_Analysis/2_metadata/genotype_metadata.xlsx"

